server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://root:pass123@localhost:27017/microservicios?authSource=admin
#      uri: mongodb://localhost:27017
#      database: microservicios
  application:
    name: CALIFICACION-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka