server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservicios
    username : postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: HOTEL-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#  config:
#    import: optional:configserver:http://localhost:8085